apiVersion: apps/v1
kind: Deployment
metadata:
  name: jkpgnav-deployment
  namespace: jkpgcity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jkpgnav
  template:
    metadata:
      labels:
        app: jkpgnav
    spec:
      containers:
      - name: jkpgnav
        env:
        - name: DB_HOST
          value: "172.17.0.1"
        image: localhost:5000/jkpgnav